const historyData = [
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
  {
    type: '',
    from: 'Me',
    to: 'Alice',
    status: 'Failed',
    amout: '5000',
    date: '10-02-2023',
  },
];
export default historyData;
